/*!
@copyright
Copyright (c) 2020, Kilian Kegel. All rights reserved.<BR>
SPDX-License-Identifier: BSD-2-Clause-Patent

@file EfiCallerGuid.c

@brief C Development Environment (CDE) driver name\n
Supply of the drivers / executables name, for the CDEMOFINE trace infrastructure.\n\n
In the EDK build process this file must not be used, since
'EfiCallerGuid' is automatically generated by the build process.


*/
typedef struct _GUID {unsigned long  Data1;unsigned short Data2;unsigned short Data3;unsigned char  Data4[8];} GUID;
GUID gEfiCallerIdGuid = { 0xCDE000FF,0xFFFF,0xFFFF,0xFF,0xFF,0xFF ,0xFF ,0xFF ,0xFF ,0xFF ,0xFF };